export default {
    // FETCH_COLLABORATORS: 'FETCH_COLLABORATORS',
    ADD_COLLABORATOR: 'ADD_COLLABORATOR',
    REMOVE_COLLABORATOR: 'REMOVE_COLLABORATOR',
    FETCH_WORKSPACE: 'FETCH_WORKSPACE',
    TOGGLE_PAGE_VIEW: 'TOGGLE_PAGE_VIEW'
};
