export default {
    FETCH_PROFILE: 'FETCH_PROFILE',
    TOGGLE_PAGE_VIEW: 'TOGGLE_PAGE_VIEW',
    SET_USER_ID: 'SET_USER_ID',
    GET_PROFILE: 'GET_PROFILE',
    INVITE: 'INVITE',
    LOGOUT: 'LOGOUT'
};
