export default {
    EDIT_TITLE_ON: 'EDIT_TITLE_ON',
    EDIT_TITLE_OFF: 'EDIT_TITLE_OFF',
    PLAY_AUDIO: 'PLAY_AUDIO',
    FETCH_WORKSPACE: 'FETCH_WORKSPACE',
    RESET_WORKSPACE: 'RESET_WORKSPACE',
    TOGGLE_WORKSPACE_PAGE_VIEW: 'TOGGLE_WORKSPACE_PAGE_VIEW',
    SUBMIT_TITLE_FORM: 'SUBMIT_TITLE_FORM',
    CHANGE_TITLE_FORM: 'CHANGE_TITLE_FORM'
};
