export default {
    FETCH_COMMENTS: 'FETCH_COMMENTS',
    RESET_WORKSPACE: 'RESET_WORKSPACE',
    UPDATE_COMMENTS_CURRENT_AUDIO: 'UPDATE_COMMENTS_CURRENT_AUDIO',
    UPDATE_NEW_COMMENT: 'UPDATE_NEW_COMMENT'
};
