export default {
    // FETCH_COLLABORATORS: 'FETCH_COLLABORATORS',
    FETCH_INVITES: 'FETCH_INVITES',
    ACCEPT_INVITE: 'ACCEPT_INVITE',
    DECLINE_INVITE: 'DECLINE_INVITE',
    CANCEL_INVITE: 'CANCEL_INVITE',
    TOGGLE_INVITES_VIEW: 'TOGGLE_INVITES_VIEW',
    INVITE: 'INVITE',
    FETCH_PROFILE: 'FETCH_PROFILE'
};
